# Generated by Django 4.1 on 2022-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroy_name', models.CharField(max_length=150)),
                ('category_desc', models.TextField()),
                ('categroy_img', models.ImageField(upload_to='category_img/')),
                ('category_tag', models.CharField(choices=[('laptops', 'laptops'), ('mobiles', 'mobiles'), ('shirts', 'shirts')], max_length=7)),
            ],
        ),
    ]
