# Generated by Django 4.1 on 2022-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categroy_img',
            field=models.ImageField(upload_to='static/images/category_img/'),
        ),
    ]
