# Generated by Django 4.1 on 2022-09-02 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_desc', models.TextField()),
                ('product_price', models.PositiveIntegerField()),
                ('product_discount_price', models.PositiveIntegerField()),
                ('product_img', models.ImageField(upload_to='prodcutImages/')),
                ('prodcut_size', models.CharField(blank=True, max_length=50, null=True)),
                ('prodcut_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
            ],
        ),
    ]
